#! /bin/bash

echo -e "███████╗ ██████╗ ███╗   ██╗"
echo -e "██╔════╝██╔═══██╗████╗  ██║"
echo -e "█████╗  ██║   ██║██╔██╗ ██║"
echo -e "██╔══╝  ██║   ██║██║╚██╗██║"
echo -e "███████╗╚██████╔╝██║ ╚████║"
echo -e "╚══════╝ ╚═════╝ ╚═╝  ╚═══╝"
echo -e "=== created by darrontd ==="
echo
echo "Instructions"
echo "> Enter a single epoch timestamp"
echo "> or enter one by line, or paste"
echo "> multiple in a block."
echo "> It will attempt to use epoch"
echo "> seconds first, then milliseconds."
echo "> To start converting press enter twice."
echo "----------------------------------------"

# Initialize empty text file
touch temp.txt

# Start read loop
while IFS= read -r -p "" line; do
    [[ $line ]] || break
    # Append entered line to a temp text file
    echo $line >> temp.txt
done

echo "Timestamps in GMT+0"
echo "-------------------"
# Call python
python3 epoch.py --times='temp.txt'

# Remove temp file
rm temp.txt

echo
echo "Done!"
