#! /bin/bash

echo -e "███████╗ ██████╗ ███╗   ██╗"
echo -e "██╔════╝██╔═══██╗████╗  ██║"
echo -e "█████╗  ██║   ██║██╔██╗ ██║"
echo -e "██╔══╝  ██║   ██║██║╚██╗██║"
echo -e "███████╗╚██████╔╝██║ ╚████║"
echo -e "╚══════╝ ╚═════╝ ╚═╝  ╚═══╝"
echo -e "=== created by darrontd ==="
echo
echo "Instructions"
echo "> Enter a single epoch timestamp"
echo "> or enter one by line, or paste"
echo "> multiple in a block."
echo "> It will attempt to use epoch"
echo "> seconds first, then milliseconds."
echo "> To start converting press enter twice."
echo "----------------------------------------"

# Initialize empty array
timelines=()

# Start read loop
while IFS= read -r -p "" line; do
    [[ $line ]] || break
    timelines+=("$line")
done

echo $timelines
# Write array to temp file
echo $timelines > temp

# Call python
python3 epoch.py --times='temp'

# Remove temp file
rm temp

echo
echo "Done!"
